# Generated by Django 6.0.7 on 2026-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_code_url',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
