# Generated by Django 6.0.7 on 2026-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_project_view_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_url',
            field=models.URLField(default="https://i.pinimg.com/736x/a8/08/35/a808353507aa0bd01a6812a412240758.jpg'"),
        ),
    ]
