# Generated by Django 6.0.7 on 2026-07-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
