# Generated by Django 6.0.7 on 2026-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_skills_slug_alter_skills_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
