# Generated by Django 6.0.7 on 2026-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0010_professional_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_experience',
            name='details',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
    ]
